// Radio Button extension for Gig Performer by @rank13
#include <vector>

// List of panels: the names that appear in the GP UI, and the filenames for custom user-created panels
std::vector<std::string> panelNames = { "Radio Buttons x 2", "Radio Buttons x 4", "Radio Buttons x 8", "Radio Buttons x 16"};
std::vector<std::string> userPanelNames = { "RadioButtons2.gppanel", "RadioButtons4.gppanel", "RadioButtons8.gppanel", "RadioButtons16.gppanel" };

// XML for the default included panels
std::vector<std::string> panelXML = {              
"<RACKUNIT size=\"10\" style=\"0\" color=\"ff000000\" ver=\"4.099999904632568\">"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.1535769828926905\" y=\"0.5294117647058824\""
"          width=\"0.1298600311041991\" height=\"0.7058823529411765\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.1655629139072848\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"3f636363\" outlineColor=\"fff5f5f5\" outlineRound=\"5\""
"          outlineThick=\"1\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1255832037325039\" y=\"0.6402714932126696\""
"          width=\"0.03965785381026438\" height=\"0.3393665158371041\" caption=\"1\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_1_1\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"  </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1761275272161742\" y=\"0.6402714932126696\""
"          width=\"0.03965785381026438\" height=\"0.3393665158371041\" caption=\"2\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" backPlate=\"11\" backPlateVisible=\"1\" invertMIDI=\"0\""
"          displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\" relativeMode=\"0\""
"          enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\" directedOSCIPAddress=\"\""
"          directedOSCPort=\"9001\" directedOSCTargetName=\"\" widgetDirectedOSCType=\"0\""
"          widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_1_2\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.5042768273716952\" y=\"0.5429864253393665\""
"          width=\"0.4175738724727838\" height=\"0.7239819004524887\" caption=\"Additional radio buttons can be added (up to 16) by entering a name for any new widget in the widget settings 'Advanced' tab, in the format: RADIO_1_3 - where the first number is the radio button group, and the second number is the unique button number.\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"1\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.06451612903225806\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" fontSize=\"22.0\" textPos=\"36\" textColor=\"ffffffff\""
"          usesDimming=\"1.0\">"
"  </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.1542857142857143\" y=\"0.3009478672985782\""
"          width=\"0.1322448979591837\" height=\"0.2417061611374408\" caption=\"Radio Buttons\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.196078431372549\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" fontSize=\"24.0\" textPos=\"36\" textColor=\"ffffffff\""
"          usesDimming=\"1.0\">"
"  </WIDGET>"
"</RACKUNIT>"
,
"<RACKUNIT size=\"10\" style=\"0\" color=\"ff4682b4\" ver=\"4.099999904632568\">"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.2020408163265306\" y=\"0.495260663507109\""
"          width=\"0.2277551020408163\" height=\"0.7061611374407583\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.1677852348993289\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"3f636363\" outlineColor=\"fff5f5f5\" outlineRound=\"5\""
"          outlineThick=\"1\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1253061224489796\" y=\"0.6066350710900474\""
"          width=\"0.04\" height=\"0.3412322274881517\" caption=\"1\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.3194444444444444\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"1.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_2_1\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1751020408163265\" y=\"0.6066350710900474\""
"          width=\"0.04\" height=\"0.3412322274881517\" caption=\"2\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.3194444444444444\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_2_2\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.2257142857142857\" y=\"0.6066350710900474\""
"          width=\"0.04\" height=\"0.3412322274881517\" caption=\"3\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.3194444444444444\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_2_3\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.2755102040816326\" y=\"0.6066350710900474\""
"          width=\"0.04\" height=\"0.3412322274881517\" caption=\"4\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\" overrideName=\"1\""
"          captionVisible=\"1\" captionHeight=\"0.3194444444444444\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_2_4\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.2004081632653061\" y=\"0.2890995260663507\""
"          width=\"0.1902040816326531\" height=\"0.2464454976303317\" caption=\"Radio Buttons\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.2115384615384615\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" fontSize=\"24.0\" textPos=\"36\" textColor=\"ffffffff\""
"          usesDimming=\"1.0\">"
"      </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.6\" y=\"0.471563981042654\" width=\"0.4179591836734694\""
"          height=\"0.7251184834123223\" caption=\"Additional radio buttons can be added (up to 16) by entering a name for any new widget in the widget settings 'Advanced' tab, in the format: RADIO_2_5 - where the first number is the radio button group, and the second number is the unique button number.\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"1\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.06451612903225806\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" fontSize=\"22.0\" textPos=\"36\" textColor=\"ffffffff\""
"          usesDimming=\"1.0\">"
"      </WIDGET>"
"</RACKUNIT>"
,
"<RACKUNIT size=\"10\" style=\"0\" color=\"ff4682b4\" ver=\"4.099999904632568\">"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.3028571428571429\" y=\"0.5\" width=\"0.4277551020408163\""
"          height=\"0.7061611374407583\" caption=\"\" captionIncludesAttribute=\"0\""
"          hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\" overrideName=\"1\""
"          captionVisible=\"0\" captionHeight=\"0.1677852348993289\" reflectMIDI=\"\""
"          reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\" midiData=\"0\""
"          rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"3f636363\" outlineColor=\"fff5f5f5\" outlineRound=\"5\""
"          outlineThick=\"1\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1273469387755102\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"1\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_1\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1771428571428571\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"2\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_2\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.2277551020408163\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"3\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_3\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.2775510204081633\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"4\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_4\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.3012244897959184\" y=\"0.2962085308056872\""
"          width=\"0.2530612244897959\" height=\"0.2511848341232227\" caption=\"Radio Buttons\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.2272727272727273\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" fontSize=\"24.0\" textPos=\"36\" textColor=\"ffffffff\""
"          usesDimming=\"1.0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.3281632653061224\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"5\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_5\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.3779591836734694\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"6\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_6\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.4285714285714285\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"7\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_7\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.4783673469387755\" y=\"0.6113744075829384\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"8\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"0\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_3_8\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.7518367346938776\" y=\"0.471563981042654\""
"          width=\"0.4179591836734694\" height=\"0.7251184834123223\" caption=\"Additional radio buttons can be added (up to 16) by entering a name for any new widget in the widget settings 'Advanced' tab, in the format: RADIO_3_9 - where the first number is the radio button group, and the second number is the unique button number.\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"1\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.06451612903225806\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" fontSize=\"22.0\" textPos=\"36\" textColor=\"ffffffff\""
"          usesDimming=\"1.0\">"
"      </WIDGET>"
"</RACKUNIT>"
,
"<RACKUNIT size=\"10\" style=\"0\" color=\"ff4682b4\" ver=\"4.099999904632568\">"
"  <WIDGET type=\"5\" style=\"0\" x=\"0.5028571428571429\" y=\"0.518957345971564\""
"          width=\"0.8261224489795919\" height=\"0.7061611374407583\" caption=\"\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.1610738255033557\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"3f636363\" outlineColor=\"fff5f5f5\" outlineRound=\"5\""
"          outlineThick=\"1\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1257142857142857\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"1\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_1\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.1755102040816326\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"2\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_2\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.2253061224489796\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"3\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_3\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.2759183673469388\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"4\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_4\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"4\" style=\"0\" x=\"0.4983673469387755\" y=\"0.3199052132701422\""
"          width=\"0.2538775510204082\" height=\"0.2511848341232227\" caption=\"Radio Buttons\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"0\" captionHeight=\"0.2272727272727273\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"1.0\" backPlate=\"10\" backPlateVisible=\"0\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" fontSize=\"24.0\" textPos=\"36\" textColor=\"ffffffff\""
"          usesDimming=\"1.0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.3257142857142857\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"5\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_5\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.3755102040816327\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"6\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_6\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.4253061224489796\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"7\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_7\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.4751020408163265\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"8\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_8\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.5265306122448979\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"9\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_9\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.5763265306122449\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"10\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_10\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.6253061224489795\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"11\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_11\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.6751020408163265\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"12\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_12\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.7248979591836735\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"13\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_13\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.7755102040816326\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"14\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_14\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.8253061224489796\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"15\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_15\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"  <WIDGET type=\"3\" style=\"0\" x=\"0.8751020408163265\" y=\"0.6303317535545023\""
"          width=\"0.04081632653061224\" height=\"0.3412322274881517\" caption=\"16\""
"          captionIncludesAttribute=\"0\" hideTemporaryValueDisplay=\"1\" hideInPresentationView=\"0\""
"          overrideName=\"1\" captionVisible=\"1\" captionHeight=\"0.3194444444444444\""
"          reflectMIDI=\"\" reflectMIDIOn=\"0\" midiThru=\"0\" midiSource=\"\" midiDevice=\"\""
"          midiData=\"0\" rigId=\"0\" widgetValue=\"0.0\" backPlate=\"11\" backPlateVisible=\"1\""
"          invertMIDI=\"0\" displayRange=\"0\" ignoresVariations=\"0\" followHardware=\"0\""
"          relativeMode=\"0\" enableDirectedOSC=\"0\" directedOSCAddressPattern=\"\""
"          directedOSCIPAddress=\"\" directedOSCPort=\"9001\" directedOSCTargetName=\"\""
"          widgetDirectedOSCType=\"0\" widgetDirectedMinIntValue=\"0\" widgetDirectedMaxIntValue=\"127\""
"          widgetDirectedMinDoubleValue=\"0.0\" widgetDirectedMaxDoubleValue=\"1.0\""
"          widgetDirectedStringListValue=\"\" widgetHandle=\"RADIO_4_16\" enableOSC=\"0\""
"          invertOSC=\"0\" groupName=\"\" widgetMoveBehavior=\"0\" updateOnLoadGig=\"0\""
"          updateOnActivateRackspace=\"0\" setDefaultDoubleClickResetValue=\"0.0\""
"          bckgColor=\"ff3c3c3c\" outlineColor=\"ff808080\" outlineRound=\"4\""
"          outlineThick=\"2\" btnMomToLatch=\"0\" btnPadLike=\"0\">"
"      </WIDGET>"
"</RACKUNIT>"
};